// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cyruzin/puppet_master/domain"
	mock "github.com/stretchr/testify/mock"
)

// PermissionUsecase is an autogenerated mock type for the PermissionUsecase type
type PermissionUsecase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PermissionUsecase) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx
func (_m *PermissionUsecase) Fetch(ctx context.Context) ([]*domain.Permission, error) {
	ret := _m.Called(ctx)

	var r0 []*domain.Permission
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Permission)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PermissionUsecase) GetByID(ctx context.Context, id int64) (*domain.Permission, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Permission
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Permission)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, permission
func (_m *PermissionUsecase) Store(ctx context.Context, permission *domain.Permission) error {
	ret := _m.Called(ctx, permission)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, permission
func (_m *PermissionUsecase) Update(ctx context.Context, permission *domain.Permission) error {
	ret := _m.Called(ctx, permission)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
