version: "3.9"

services:
  database:
    image: postgres:13.2-alpine
    container_name: puppet_master-postgres
    hostname: puppet_master-postgres
    volumes:
      - .data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=puppet_master
      - POSTGRES_USER=puppet
      - POSTGRES_PASSWORD=master

  redis:
    image: redis:6.2.1-alpine
    container_name: puppet_master-redis
    hostname: puppet_master-redis
    volumes:
      - .data/redis:/data
    command: redis-server --requirepass master --appendonly yes
    ports:
      - 6379:6379

  adminer:
    image: adminer
    ports:
      - 8080:8080
